spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:tcp:test
    username: test
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true